### ISSUE TITLE
To-Do list for publishing to GF

### ISSUE THREAD

**Issue by vv-monsalve** [TypeTogether/Playpen-Sans#1]
The following are the main points to cover in preparation to onboard the fonts to GF.

- [x] Arrange the repo structure to meet [our requirements](https://googlefonts.github.io/gf-guide/upstream.html#the-essentials-explained). Mainly:
    - Only the required source files to build the fonts, not process intermediates. Ideally, it's a single file
    - All the build scripts required (if any)
    - Fonts directory, including only the latest version
    - README file with the information of the project, including building instructions
  
- [x] The fonts follow our [technical requirements](https://googlefonts.github.io/gf-guide/variable.html). Running Fontbakery on the variable font at `test-proof/S17_Sensei-informal_20230322`, there are many reported fails. The most crucial for now is related to Vertical metrics.
    - 🔥 FAIL OS/2 sTypoAscender (800) and hhea ascent (936) must be equal. [code: ascender]

- [x] Update the README.md file providing detailed info for the project. It should include at least one image and the current building instructions of the font. You can find more details about the [Readme file](https://googlefonts.github.io/gf-guide/readmefile) in the GF-Guide.
